### ISSUE TITLE
Design details for InstructionValue

### ISSUE THREAD

**Issue by junlarsen** [junlarsen/llvm4j#70]
This continues the topic which was slightly touched upon in #62 

We have a couple options when it comes to designing the wrapper for Instruction values. We could group every single type of instruction under one single class, InstructionValue or we could have a lot of child classes which all extend InstructionValue. Similar to how we have Value and *Value types.

**Pros**
- Everything is more explicit, there are a set of operations for each different type
- Lower probability for segfaults as we know everything should work for said instruction
- We've already implemented something similar (Types & Values)

**Cons**
- This requires a lot more work than grouping everything under one type

**Comment by junlarsen** [comment]
Would like to hear your thoughts on this one @dhruvrajvanshi. I personally think making a class for each instruction type will make everything easier to work with.

**Comment by dhruvrajvanshi** [comment]
There are 2 really important benefits I can see for separating out the types of instructions:
1. Preventing segfaults/module invalidations at compile time. This is THE reason we should do this. Even though module.verify() and function.verify() do a decent job, it doesn't cover all the bases and it would be nice to move the cases which it does cover to compile time.

2. Consistency with LLVM C++ API type hierarchy: Easier to tie these apis back to the C++ documentation (which is much better categorized than the C binding api). Pretty nice to have but not really essential.

**That being said, it doesn't make too much sense to put too much effort up front for not that much benefit.**

I think, we could start by having Builder::build* methods return just `Instruction`, then, as we identify, potential segfault/invariant locations, we can break out separate subclasses for them as the need arises. Maybe create a tracking issue to add potential type safety candidates.

We should have 1 class per underlying LLVM C++ type and a bunch of composable contract interfaces that would narrow down builder arguments.

For example, buildStore requires a valid pointer as its argument that we can load from. This could come from buildAlloca, getGlobal, etc. there could be a Storeable interface (that could just be a empty marker interface) and AllocaInstruction and PointerValue could implement that. Now we can narrow down the type of buildStore to only take things that implement Storeable. That would be awesome and we might even move beyond LLVM C++ API's own type safety.

**Comment by junlarsen** [comment]
I agree, just using Instruction sounds good for now and then we'll swap it out later.

**Comment by dhruvrajvanshi** [comment]
So I was working on creating a mid-level IR for my language that lowers to LLVM. I tested out the idea of having multiple composable interfaces at that level. Here's what I found out:

1. The idea of having builders return concrete values implement multiple interfaces doesn't work out well.

2. **Having subtypes of Instruction value is required for writing analysis passes**, so that will have to be done eventually. (I'll start implementing that when I need to write LLVM level passes, which I'm not doing right now. All my transformation passes are at the mid level IR level).

**Comment by junlarsen** [comment]
1. So it's "better" to write overloads for functions which accept different types instead of interfaces? (see pt 2)
1. Thought so, so should implement subtypes regardless?

**Comment by dhruvrajvanshi** [comment]
1. With regards to overloads, IMO we should be doing what llvm c++ api is doing unless there's a good reason to diverge.

2. Yes, I believe so. I don't know how you want to prioritise that though. Because I won't be writing LLVM level passes any time soon, I won't really be able to contribute anything useful on that front.
